// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RepPay.API.Models;

#nullable disable

namespace RepPay.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status_despesa", new[] { "ATIVA", "QUITADA", "CANCELADA" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status_parcela", new[] { "PENDENTE", "PAGO", "ATRASADO" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pertence", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("integer")
                        .HasColumnName("id_grupo");

                    b.HasKey("IdUsuario", "IdGrupo")
                        .HasName("pertence_pkey");

                    b.HasIndex("IdGrupo");

                    b.ToTable("pertence", (string)null);
                });

            modelBuilder.Entity("RepPay.API.Models.CodigoRecuperacao", b =>
                {
                    b.Property<int>("IdCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_codigo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCodigo"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<bool>("CodigoUsado")
                        .HasColumnType("boolean")
                        .HasColumnName("codigo_usado");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_expiracao");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas");

                    b.HasKey("IdCodigo");

                    b.ToTable("codigo_recuperacao");
                });

            modelBuilder.Entity("RepPay.API.Models.Despesa", b =>
                {
                    b.Property<int>("IdDespesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_despesa");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDespesa"));

                    b.Property<DateOnly>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("data_cadastro")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<string>("Icone")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icone");

                    b.Property<int>("IdGrupo")
                        .HasColumnType("integer")
                        .HasColumnName("id_grupo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor");

                    b.Property<DateOnly>("Vencimento")
                        .HasColumnType("date")
                        .HasColumnName("vencimento");

                    b.HasKey("IdDespesa")
                        .HasName("despesa_pkey");

                    b.HasIndex("IdGrupo");

                    b.ToTable("despesa", (string)null);
                });

            modelBuilder.Entity("RepPay.API.Models.Grupo", b =>
                {
                    b.Property<int>("IdGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_grupo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdGrupo"));

                    b.Property<string>("CodigoAcesso")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_acesso");

                    b.Property<int>("IdAdmin")
                        .HasColumnType("integer")
                        .HasColumnName("id_admin");

                    b.Property<string>("ImagemBanner")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("imagem_banner");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("IdGrupo")
                        .HasName("grupo_pkey");

                    b.HasIndex("IdAdmin");

                    b.HasIndex(new[] { "CodigoAcesso" }, "grupo_codigo_acesso_key")
                        .IsUnique();

                    b.ToTable("grupo", (string)null);
                });

            modelBuilder.Entity("RepPay.API.Models.Parcela", b =>
                {
                    b.Property<int>("IdParcela")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_parcela");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdParcela"));

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date")
                        .HasColumnName("data_pagamento");

                    b.Property<int>("IdDespesa")
                        .HasColumnType("integer")
                        .HasColumnName("id_despesa");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor");

                    b.HasKey("IdParcela")
                        .HasName("parcela_pkey");

                    b.HasIndex(new[] { "IdDespesa" }, "idx_parcela_despesa");

                    b.HasIndex(new[] { "IdUsuario", "IdDespesa" }, "parcela_id_usuario_id_despesa_key")
                        .IsUnique();

                    b.ToTable("parcela", (string)null);
                });

            modelBuilder.Entity("RepPay.API.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha");

                    b.HasKey("IdUsuario")
                        .HasName("usuario_pkey");

                    b.HasIndex(new[] { "Email" }, "usuario_email_key")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Pertence", b =>
                {
                    b.HasOne("RepPay.API.Models.Grupo", null)
                        .WithMany()
                        .HasForeignKey("IdGrupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pertence_grupo");

                    b.HasOne("RepPay.API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pertence_usuario");
                });

            modelBuilder.Entity("RepPay.API.Models.Despesa", b =>
                {
                    b.HasOne("RepPay.API.Models.Grupo", "IdGrupoNavigation")
                        .WithMany("Despesas")
                        .HasForeignKey("IdGrupo")
                        .IsRequired()
                        .HasConstraintName("fk_despesa_grupo");

                    b.Navigation("IdGrupoNavigation");
                });

            modelBuilder.Entity("RepPay.API.Models.Grupo", b =>
                {
                    b.HasOne("RepPay.API.Models.Usuario", "IdAdminNavigation")
                        .WithMany("Grupos")
                        .HasForeignKey("IdAdmin")
                        .IsRequired()
                        .HasConstraintName("fk_admin_grupo");

                    b.Navigation("IdAdminNavigation");
                });

            modelBuilder.Entity("RepPay.API.Models.Parcela", b =>
                {
                    b.HasOne("RepPay.API.Models.Despesa", "IdDespesaNavigation")
                        .WithMany("Parcelas")
                        .HasForeignKey("IdDespesa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parcela_despesa");

                    b.HasOne("RepPay.API.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Parcelas")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("fk_parcela_usuario");

                    b.Navigation("IdDespesaNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("RepPay.API.Models.Despesa", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("RepPay.API.Models.Grupo", b =>
                {
                    b.Navigation("Despesas");
                });

            modelBuilder.Entity("RepPay.API.Models.Usuario", b =>
                {
                    b.Navigation("Grupos");

                    b.Navigation("Parcelas");
                });
#pragma warning restore 612, 618
        }
    }
}
